<?php
/** @var $this BurnOut_ProductPart_Block_Adminhtml_Catalog_Product_Helper_Gallery_SwatchesGrids */
?>
<div id="<?php echo $this->getId() ?>" style="<?php echo $this->getExtraCss() ?>">
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
                <?php foreach ($this->getColumns() as $_column): ?>
                    <col <?php echo $_column->getHtmlProperty() ?> />
                <?php endforeach; ?>
                <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
                    <thead>
                    <tr class="headings">
                        <th colspan="<?php echo count($this->getColumns()); ?>" align="center">
                            <?php echo $this->getGridTitle() ?>
                        </th>
                    </tr>
                    <?php if ($this->getHeadersVisibility()): ?>
                        <tr class="headings">
                            <?php foreach ($this->getColumns() as $_column): ?>
                                <th<?php echo $_column->getHeaderHtmlProperty() ?>><span
                                        class="nobr"><?php echo $_column->getHeaderHtml() ?></span></th>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                    <tr class="filter">
                        <?php $i = 0;
                        foreach ($this->getColumns() as $_column): ?>
                            <th<?php echo $_column->getHeaderHtmlProperty() ?>><?php echo $_column->getFilterHtml() ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                <?php endif; ?>
                <tbody>
                <?php if (($this->getCollection()->getSize() > 0) && (!$this->getIsCollapsed())): ?>
                    <?php foreach ($this->getCollection() as $_index => $_item): ?>
                        <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)): ?> class="<?php echo $_class; ?>"<?php endif; ?> >
                            <?php $i = 0;
                            foreach ($this->getColumns() as $_column): ?>
                                <?php if ($this->shouldRenderCell($_item, $_column)): ?>
                                    <?php $_rowspan = $this->getRowspan($_item, $_column); ?>
                                    <td filter_index="<?php echo $_column->getIndex() ?>"
                                        <?php echo($_rowspan ? 'rowspan="' . $_rowspan . '" ' : '') ?>class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i == $numColumns ? 'last' : '' ?>">
                                        <?php echo(($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?>
                                    </td>
                                    <?php if ($this->shouldRenderEmptyCell($_item, $_column)): ?>
                                        <td colspan="<?php echo $this->getEmptyCellColspan($_item) ?>"
                                            class="last"><?php echo $this->getEmptyCellLabel() ?></td>
                                    <?php endif; ?>
                                <?php endif; ?>

                            <?php endforeach; ?>
                        </tr>
                        <?php if ($_multipleRows = $this->getMultipleRows($_item)): ?>
                            <?php foreach ($_multipleRows as $_i): ?>
                                <tr>
                                    <?php $i = 0;
                                    foreach ($this->getMultipleRowColumns($_i) as $_column): ?>
                                        <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i == $numColumns - 1 ? 'last' : '' ?>">
                                            <?php echo(($_html = $_column->getRowField($_i)) != '' ? $_html : '&nbsp;') ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>


                    <?php endforeach; ?>
                <?php elseif ($this->getEmptyText()): ?>
                    <tr>
                        <td class="empty-text <?php echo $this->getEmptyTextClass() ?>"
                            colspan="<?php echo $numColumns ?>"><?php echo $this->getEmptyText() ?></td>
                    </tr>
                <?php endif; ?>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <input type="hidden" name="<?php echo $this->getSerializerId() ?>" value=""
           id="<?php echo $this->getSerializerId() ?>"/>
</div>








