<?php
/**
 * @var $this Burnout_Uploader_Block_Media_Uploader
 */
?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('burnout_uploader/uploader/jsuploader.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('burnout_uploader/uploader/uploader.js') ?>

<style>
    .dropbox-wrapper {
        background: #D7E5EF;
        padding: 8px;
    }

    .dropbox {
        padding: 5px;
        line-height: 60px;
        border: 2px dashed #06a;
        text-align: center;
        font-weight: bold;
        font-size: medium;
        color: #06a;
        margin: 12px;
    }

    .dropbox.active {
        background: #bdbbbb;
    }
</style>

<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <?php if ($this->getUploaderConfig()->getUseNativeGrid()): ?>
        <div class="grid">
            <table cellspacing="0" class="data border" id="<?php echo $this->getHtmlId() ?>_attachment_table"
                   width="100%">
                <col/>
                <col width="20">
                <thead>
                <tr class="headings">
                    <th><?php echo $this->__('Filename') ?></th>
                    <th class="last"><?php echo Mage::helper('catalog')->__('Remove') ?></th>
                </tr>
                </thead>
                <tbody id="<?php echo $this->getHtmlId() ?>-attachment_list">
                <tr id="<?php echo $this->getHtmlId() ?>-attachment_template" class="template no-display">
                    <td class="cell-file">
                        <span><a href="__url__" target="_blank">__name__</a></span>
                    </td>
                    <td class="cell-remove a-center last">
                        <?php if ($this->getUploaderConfig()->getUseDirectUpload()): ?>
                            <a href="#"
                               onclick="<?php echo $this->getJsObjectName(); ?>.removeGridFile('__file__');return false;">
                                <img src="<?php echo $this->getSkinUrl('images/cancel_icon.gif'); ?>"
                                     alt="<?php echo $this->__("Remove Attachment"); ?>">
                            </a>
                        <?php else: ?>
                            <input type="checkbox"
                                   onclick="<?php echo $this->getJsObjectName(); ?>.removeGridFile('__file__')"/>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr id="<?php echo $this->getHtmlId() ?>-file-0">
                    <td class="cell-file">
                        <?php echo Mage::helper('catalog')->__('No attachment') ?>
                    </td>
                    <td class="cell-remove last">
                        <input type="hidden"/>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
    <div class="dropbox-wrapper">
        <div class="buttons">
            <input type="file" id="<?php echo $this->getHtmlId() ?>-file" multiple name="image"/>
            <span style="float:right"><?php echo $this->getUploadButtonHtml() ?></span>
        </div>
        <div class="clear"></div>
        <div id="<?php echo $this->getHtmlId() ?>-dropbox" class="dropbox">Drag and Drop Files Here</div>
        <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
            <div id="{{id}}" class="file-row">
                <span class="file-info">{{name}}</span>
                <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
                <span class="progress-text"></span>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getJsObjectName() ?> = new JsUploader('<?php echo $this->getHtmlId() ?>', <?php echo $this->getJsonConfig() ?>);
    //]]>
</script>