<?php
$this->_initDone = true;
$attributeModel = Mage::registry('entity_attribute');
$bSwatchHelper = Mage::helper('burnout_configurableswatches');
$dimHelper = Mage::helper('configurableswatches/swatchdimensions');

$optionList = $bSwatchHelper->getAttributebOptions($attributeModel);
$width = $dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_DETAIL);
$height = $dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_DETAIL);
?>

<div>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo $bSwatchHelper->__('To use auto swatches, please go to Manage Label / Options and enter the HEX code of your color in the Admin value field. Example: Green #83F52C<br>The preview image below is exactly how your swatch will look based on your default swatch size setting in the configuration.') ?>
                </li>
            </ul>
        </li>
    </ul>
</div>

<div class="entity-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $bSwatchHelper->__('Manage Swatches') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table cellspacing="10">
                <tr>
                    <th width="150"><?php echo $bSwatchHelper->__('Swatch Label') ?></th>
                    <th width="15"></th>
                    <th width="250"><?php echo $bSwatchHelper->__('Upload Swatch Image') ?></th>
                    <th width="15"></th>
                    <th><?php echo $bSwatchHelper->__('Preview') ?></th>
                    <th width="15"></th>
                    <th><?php echo $bSwatchHelper->__('Swatch Type') ?></th>
                    <th width="15"></th>
                    <th><?php echo $bSwatchHelper->__('HEX Code') ?></th>
                    <th width="15"></th>
                    <th><?php echo $bSwatchHelper->__('Delete') ?></th>
                </tr>
                <?php $image_swatch_url_empty = $this->getSwatchUrl('empty'); ?>
                <?php foreach ($optionList as $option): ?>
                    <tr class="<?php echo $option->getData('option_id'); ?>">
                        <?php
                        $image_swatch_url = $this->getSwatchUrl($option->getData('option_id'));

                        $optionLabel = explode('#', $option->getData('value'));
                        $color_value = isset($optionLabel[1]) ? '#' . $optionLabel[1] : '';
                        $color_name = $optionLabel[0];
                        ?>
                        <td><?php echo $color_name; ?></td>
                        <td></td>
                        <td>
                            <div
                                id="upload_swatch_area_<?php echo $option->getData('option_id'); ?>">
                                <a href="#"
                                   onclick="addUpload(<?php echo $option->getData('option_id'); ?>); return false;">
                                    <?php echo ($image_swatch_url || $color_value) ? $bSwatchHelper->__('Edit Swatch Image') : $bSwatchHelper->__('Add Swatch Image') ?>
                                </a>
                            </div>
                        </td>
                        <td></td>
                        <td align="center">
                            <?php if ($image_swatch_url): ?>
                                <img src="<?php echo $image_swatch_url; ?>" alt="<?php echo $color_name; ?>"
                                     width="<?php echo $width ?>px" height="<?php echo $height ?>px">
                                <?php $auto = $bSwatchHelper->__('Image'); ?>
                            <?php elseif (isset($theName[1])): ?>
                                <?php echo '<div style="height:' . $height . 'px; width:' . $width . 'px; background-color:' . $color_value . ';"></div>'; ?>
                                <?php $auto = $bSwatchHelper->__('Auto'); ?>
                            <?php
                            else: ?>
                                <img src="<?php echo $image_swatch_url; ?>" alt="Please Upload Swatch!"
                                     width="<?php echo $width ?>px" height="<?php echo $height ?>px">
                                <?php $auto = $bSwatchHelper->__('None'); ?>
                            <?php endif; ?>
                        </td>
                        <td></td>
                        <td align="center"><?php echo $auto; ?></td>
                        <td></td>
                        <td align="center">
                            <?php echo isset($optionLabel[1]) ? strtoupper($color_value) : '-'; ?>
                        </td>
                        <td></td>
                        <td align="center">
                            <input <?php if ($auto !== 'Image') echo 'disabled="disabled"'; ?>
                                type="checkbox" value="1"
                                name="swatch_delete[<?php echo $option->getData('option_id'); ?>]">
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
<?php $ini_setting = ini_get('max_file_uploads') ? ini_get('max_file_uploads') : 20; ?>
<script type="text/javascript">
    document.maximumUploads = <?php echo($ini_setting); ?>;
    document.potentialUploads = 0;
    function addUpload(ID) {
        var newField = "<input type=\"file\" name=\"swatch[" + ID + "]\">";
        ++document.potentialUploads;

        if (document.potentialUploads > document.maximumUploads) {
            alert("<?php echo $bSwatchHelper->__('Sorry, this server allows a maximum of %s uploads at a time. Please upload the current swatches to upload more.', $ini_setting); ?>");
        } else {
            document.getElementById("upload_swatch_area_" + ID).innerHTML = newField;
        }
    }
</script>
