  <hr/>
<?php foreach ($this->getMessagesInverted() as $message): ?>
    <?php if ($message->isSourceNotify()): ?>
        <p><b><?php echo $message->getPublicMessageHeader(); ?></b></p>
        <p><pre><?php echo $message->getMessageBody(); ?></pre></p>
        <?php if(!Mage::getStoreConfig('crmticket/general/complete_ticket_chat_in_each_message'))
            break;
        ?>
        <hr/>
    <?php endif; ?>
<?php endforeach; ?>

