<div class="entry-edit">

    <div class="entry-edit-head"> 
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Supplier notification'); ?></h4> 
    </div>
    <fieldset id="my-fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><?php echo $this->__("Communication mode"); ?></td>
                <td class="input-ele">
                    <select>
                            <option value="email" >Email</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__("Packing slip file format"); ?></td>
                <td class="input-ele">
                    <select name="sup_dropshipping_export_type" id="sup_dropshipping_export_type">
                        <?php foreach ($this->getAttachmentTypes() as $k => $v): ?>
                            <option value="<?php echo $k; ?>" <?php echo ($this->getSupplier()->getsup_dropshipping_export_type() == $k ? ' selected ' : '') ?>><?php echo $v; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note"><span><?php echo $this->__('Select the attachment file format we send to supplier with customer order information.') ?></span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__("Default shipping fees"); ?></td>
                <td class="input-ele">
                    <input type="text" name="sup_dropshipping_default_shipping_fees" id="sup_dropshipping_default_shipping_fees" value="<?php echo $this->getSupplier()->getsup_dropshipping_default_shipping_fees(); ?>" />
                    <p class="note"><span><?php echo $this->__('Shipping fees to apply by default for new drop shipping purchase order.') ?></span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__("Apply shipping fees per item"); ?></td>
                <td class="input-ele">
                    <select name="sup_dropshipping_mulitply_shipping_fees" id="sup_dropshipping_mulitply_shipping_fees">
                        <?php $yesNo = array('0' => $this->__('No'), '1' => $this->__('Yes')); ?>
                        <?php foreach ($yesNo as $k => $v): ?>
                            <option value="<?php echo $k; ?>" <?php echo ($this->getSupplier()->getsup_dropshipping_mulitply_shipping_fees() == $k ? ' selected ' : '') ?>><?php echo $v; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note"><span><?php echo $this->__('If enabled, default shipping fees are multiplied with the number of products in the purchase order.') ?></span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__("Preferred method for this supplier"); ?></td>
                <td class="input-ele">
                    <select name="sup_forced_auto_dropship_mode" id="sup_forced_auto_dropship_mode">
                        <?php
                        $list = $this->getForcedModeList();
                        foreach ($list as $k => $v): ?>
                            <option value="<?php echo $k; ?>" <?php echo ($this->getSupplier()->getsup_forced_auto_dropship_mode() == $k ? ' selected ' : '') ?>><?php echo $v; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note"><span><?php echo $this->__("Force the default mode for auto dropship for this supplier"); ?></span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__("Stock steps for auto import"); ?></td>
                <td class="input-ele">
                    <select name="sup_stock_import_rouding_step" id="sup_stock_import_rouding_step">
                        <?php
                        $list = $this->getStockStepsForImport();
                        foreach ($list as $k => $v): ?>
                            <option value="<?php echo $k; ?>" <?php echo ($this->getSupplier()->getsup_stock_import_rouding_step() == $k ? ' selected ' : '') ?>><?php echo $v; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <p class="note"><span><?php echo $this->__("Enable to change the stock import by step of this value. The idea is fast up the stock import, if the precise quantity of the supplier is not important for you."); ?></span></p>
                    <p class="note"><span><?php echo $this->__("ex : by 10 : if the supplier provide 12 of stock, it will be 10. Then the supplier provide 14, it will remain 10, then the supplier provide 45, it will be updated to 40"); ?></span></p>
                    <p class="note"><span><?php echo $this->__("In all case, because the low level of stock are critical, if the value is below the step, the value will be imported as it."); ?></span></p>
                </td>
            </tr>
        </table>
    </fieldset>    


    <div class="entry-edit-head"> 
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('CSV file template'); ?></h4> 
    </div>
    <fieldset id="my-fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><?php echo $this->__('Order row') ?></td>
                <td class="input-ele">                
                    <textarea rows="3" cols="100" name="sup_dropshipping_tpl_order" id="sup_dropshipping_tpl_order"><?php echo $this->getSupplier()->getsup_dropshipping_tpl_order(); ?></textarea>
                    <p class="note"><span><?php echo $this->__("Use available codes arrounded with ") ?>{}, ie : {order_item.qty};{order_item.sku}')</span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Order items row') ?></td>
                <td class="input-ele">                
                    <textarea rows="3" cols="100" name="sup_dropshipping_tpl_order_item" id="sup_dropshipping_tpl_order_item"><?php echo $this->getSupplier()->getsup_dropshipping_tpl_order_item(); ?></textarea>
                    <p class="note"><span><?php echo $this->__("Use available codes arrounded with ") ?>{}, ie : {order_item.qty};{order_item.sku}')</span></p>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Csv Preview') ?></td>
                <td class="input-ele">
                    <p>&nbsp;</p>
                    <div style="border-style: 1px solid black;"><pre><?php echo $this->getPreview(); ?></pre></span></div>
                    <p>&nbsp;</p>
                    </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Available codes') ?></td>
                <td class="input-ele">                
                    <p><i><?php echo $this->__("Sample datas are extracted from the newest shipment in magento :") ?></i></p>
                    <?php foreach($this->getTemplateCodes() as $k => $v): ?>
                        <?php if (is_object($v)) {continue;} ?>
                        <b><?php echo $k; ?></b> : <?php echo $v; ?>,&nbsp;
                    <?php endforeach; ?>
                </td>
            </tr>
        </table>
    </fieldset>
    
    
</div>
