<?php $supplier = $this->getSupplier();?>
<div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper("purchasingdiscount")->__("Discount info")?></h4>
	    <div class="form-buttons"></div>
	</div>
	<div class="fieldset " id="purchasingdiscount_form">
	    <div class="hor-scroll">
	        <table class="form-list" cellspacing="0">
	            <tbody>
	                <tr>
					    <td class="label"><label for="sup_base_discount"><?php echo Mage::helper("purchasingdiscount")->__("Base discount")?></label></td>
					    <td class="value"><input id="sup_base_discount" name="sup_base_discount" value="<?php echo $supplier->getsup_base_discount()?$supplier->getsup_base_discount():0;?>" class="required-entry validate-digits-range digits-range-0-100 input-text" type="text">%</td>
				    </tr>
					<tr>
					    <td class="label"><label for="sup_first_additionnal_discount"><?php echo Mage::helper("purchasingdiscount")->__("Additionnal discount")?></label></td>
					    <td class="value"><input id="sup_first_additionnal_discount" name="sup_first_additionnal_discount" value="<?php echo $supplier->getsup_first_additionnal_discount()?$supplier->getsup_first_additionnal_discount():0;?>" class="required-entry validate-digits-range digits-range-0-100 input-text" type="text">%</td>
				    </tr>
					<tr>
					    <td class="label"><label for="sup_second_additionnal_discount"><?php echo Mage::helper("purchasingdiscount")->__("Additionnal2 discount")?></label></td>
					    <td class="value"><input id="sup_second_additionnal_discount" name="sup_second_additionnal_discount" value="<?php echo $supplier->getsup_second_additionnal_discount()?$supplier->getsup_second_additionnal_discount():0;?>" class="required-entry validate-digits-range digits-range-0-100 input-text" type="text">%</td>
				    </tr>
					<tr>
					    <td class="label"><label for="sup_cash_discount"><?php echo Mage::helper("purchasingdiscount")->__("Cash discount")?></label></td>
					    <td class="value"><input id="sup_cash_discount" name="sup_cash_discount" value="<?php echo $supplier->getsup_cash_discount()?$supplier->getsup_cash_discount():0;?>" class="required-entry validate-digits-range digits-range-0-100 input-text" type="text">%</td>
				    </tr>
	            </tbody>
	        </table>
	    </div>
	</div>
</div>