<div class="entry-edit">
          <div class="entry-edit-head">
               <h4 class="icon-head head-account"><?php echo $this->__('Export Stock levels at specific date'); ?></h4>

    </div>
	<div class="fieldset">
		<form  id="exportStockValue" method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl('adminhtml/stockvalue_stockvalue/ExportStockAtDate'); ?>">
			<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
			<input id="stock_id" name="stock_id" type="hidden" value="<?php echo $this->getStock()->getId(); ?>">
			<table border="0" style="margin-left: 30px;">
			<tr>
                <th class="label"><?php echo $this->__("Method");?></th>
                <td class="input-ele">
                	<select name="method" id="method">
            			<option value=""></option>
                		<?php foreach (Mage::getModel("stockvalue/stockvalue")->getStockMethodType() as $key => $value) :?>
                			<option value="<?php echo $value;?>"><?php echo $value;?></option>
                		<?php endforeach;?>
            		</select>
            		<div class="validation-advice" id="advice-required-entry-method" style="display:none;"><?php echo $this->__("This is a required field.");?></div>
            	</td>
            </tr>
            <tr>
				<th width="200" align="center"><?php echo $this->__('Begin date'); ?></th>
				<td colspan="2">
					<input type="text" id="date_begin" name="date_begin" size="8">
					<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif'); ?>" class="v-middle" id="img_calendar_date_begin" />
					<script type="text/javascript">
						Calendar.setup({
							inputField : 'date_begin',
							ifFormat : '%Y-%m-%e',
							button : 'img_calendar_date_begin',
							align : 'Bl',
							singleClick : true
						});
					</script>	
				</td>
			</tr>
			<tr>
				<th width="200" align="center"><?php echo $this->__('End date'); ?></th>
				<td colspan="2">
					<input type="text" id="date_end" name="date_end" size="8">
					<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif'); ?>" class="v-middle" id="img_calendar_date_end" />
					<script type="text/javascript">
						Calendar.setup({
							inputField : 'date_end',
							ifFormat : '%Y-%m-%e',
							button : 'img_calendar_date_end',
							align : 'Bl',
							singleClick : true
						});
					</script>	
					<div class="validation-advice" id="advice-required-entry-date_end" style="display:none;"><?php echo $this->__("This is a required field.");?></div>
					<div class="validation-advice" id="advice-required-entry-both" style="display:none;"><?php echo $this->__("Both Dates must filled or blank.");?></div>
				</td>
			</tr>
			<tr>
                <th class="label"><?php echo $this->__("Limit the PO based on current stock (for Min/Max only)");?></th>
                <td class="input-ele">
                	<select name="stock_disable_supply_needs" id="stock_disable_supply_needs">
                		<option value="0" selected="">No</option><option value="1">Yes</option>
            		</select>
            		<div class="validation-advice" id="advice-required-entry-stock_disable_supply_needs" style="display:none;"><?php echo $this->__("Can not set yes with dates.");?></div>
            	</td>
            </tr>
			<tr>
				<th width="200" align="center"></th>
				<td colspan="2"><input type="button" value="<?php echo $this->__('Export'); ?>" onclick="submitForm();"></td>
			</tr>
			</table>
		</form>
	</div>
</div>

<script>

function submitForm()
{
	document.getElementById("advice-required-entry-stock_disable_supply_needs").style = "display:none;";
	document.getElementById("advice-required-entry-both").style = "display:none;";
	document.getElementById("advice-required-entry-method").style = "display:none;";
	document.getElementById("advice-required-entry-date_end").style = "display:none;";

	if(!document.getElementById("method").value){
		document.getElementById("advice-required-entry-method").style = "display:block;";
		return;
	}
	
	if(document.getElementById("method").value == "<?php echo MDN_StockValue_Model_Stockvalue::MINBUYINGPRICE;?>" || document.getElementById("method").value == "<?php echo MDN_StockValue_Model_Stockvalue::MAXBUYINGPRICE;?>"){
		if(document.getElementById("stock_disable_supply_needs").value == "1" && (document.getElementById("date_begin").value || document.getElementById("date_end").value))
		{
			document.getElementById("advice-required-entry-stock_disable_supply_needs").style = "display:block;";
			return false;
		}
		else if((!document.getElementById("date_begin").value && document.getElementById("date_end").value) || (document.getElementById("date_begin").value && !document.getElementById("date_end").value))
		{
			document.getElementById("advice-required-entry-both").style = "display:block;";
			return false;
		}
	}

	document.getElementById("exportStockValue").submit();
}

function onChangeSelect()
{

}
</script>
