<ch-days inline-template v-for="(day,index) in days"
         :day="day"
         :key="index"
         :chcurrent="chcurrent">

    <day inline-template
         :day="day"
         :chcurrent="chcurrent">

        <div class="w3-container" :id="day" :chcurrent="chcurrent">
            <header class="w3-container w3-blue">
                <h1>{{day}}</h1>
                <div class="loader"></div>
            </header>
            <div class="w3-container program_list">
                <!--                <program inline-template>-->
                <!---->
                <!--                </program>-->
            </div>
        </div>
    </day>


</ch-days>


<!--<ch_programs-->
<!--        v-for="program in channels"-->
<!--        v-bind:key="program.id"-->
<!--        v-bind:program="program">-->
<!--</ch_programs>-->
