<ch-days v-for="day in days"
         v-bind:day="day" v-bind:current="current" inline-template>

    <div class="w3-container" v-bind:id="day">
        <header class="w3-container w3-blue">
            <h1>{{day}}</h1>
            <div class="loader"></div>
        </header>
        <div class="w3-container program_list"></div>
    </div>

</ch-days>


<!--<ch_programs-->
<!--        v-for="program in channels"-->
<!--        v-bind:key="program.id"-->
<!--        v-bind:program="program">-->
<!--</ch_programs>-->
