<ch-days inline-template
         v-for="day in days"
         :day="day">

    <div class="w3-container day">
        <header class="w3-container w3-blue">
            <h1>{{day}}</h1>
        </header>
        <!--        <ch-d v-for="(day_data ,i) in this.daylist"-->
        <!--              :ch_current="ch_current"-->
        <!--              :daylist="daylist"-->
        <!--              :day_data="day_data">-->
        <!--            :i="i">-->
        <!--            <div>{i}</div>-->
        <!--        </ch-d>-->
    </div>

</ch-days>

<!---->


<!--
<!---->
<!--            <div class="w3-container program_list">-->
<!--                <ch_program inline-template-->
<!--                            v-for="pro_data in this.day_data"-->
<!--                            :ch_current="ch_current"-->
<!--                            :data="pro_data">-->
<!--                    <div>{{data.title}}</div>-->
<!--                </ch_program>-->
<!--            </div>-->
<!--        </ch_day_program>-->