<h2><?php echo $this->getOrderLink($this->__('Order #').$this->getOrder()->getincrement_id(), $this->getOrder()->getId()); ?></h2>
<table border="0" width="100%">     
    <tr>
        <td >
            <!-- Customer information -->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Main informations'); ?></h4>
                </div>
                <div class="fieldset">
                    <b><?php echo $this->getOrder()->getStatusLabel(); ?></b>
                    <br><?php echo $this->getOrder()->getCreatedAt(); ?>
                    <br><?php echo $this->getStoreName($this->getOrder()->getStoreId()); ?>
                    <br><?php echo ($this->getOrder()->getPayment())?($this->getOrder()->getPayment()->getMethodInstance()->gettitle()):'NO Payment'; ?>
                    <br><?php echo $this->getOrder()->getShippingDescription(); ?>
                    <br><?php echo $this->__('Shipping : %s', $this->getOrder()->formatPrice($this->getOrder()->getShippingAmount() + $this->getOrder()->getshipping_tax_amount())); ?>
                    <br><b><?php echo $this->__('Total : %s', $this->getOrder()->formatPrice($this->getOrder()->getGrandTotal())); ?></b>
                </div>
            </div>
        </td>
        <td >
            <!-- Customer information -->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Billing address'); ?></h4>
                </div>
                <div class="fieldset">
                    <?php echo $this->formatAddress($this->getOrder()->getBillingAddress(),"<br/>") ?>
                </div>
            </div>
        </td>
        <td >
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shipping address'); ?></h4>
                </div>
                <div class="fieldset">
                    <?php echo $this->formatAddress($this->getOrder()->getShippingAddress(),"<br/>") ?>
                </div>
            </div>            
        </td>
    </tr>

    <tr>
        <td colspan="3">
            <!-- Products -->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Products'); ?></h4>
                </div>
                <div class="fieldset">
                    <table border="0" width="100%">
                        <tr>
                            <th><?php echo $this->__('Product'); ?></th>
                            <th class="a-center"><?php echo $this->__('Qty ordered'); ?></th>
                            <th class="a-center"><?php echo $this->__('Qty to ship'); ?></th>
                            <th class="a-center"><?php echo $this->__('Qty refunded'); ?></th>
                            <th class="a-center"><?php echo $this->__('Price'); ?></th>
                            <th class="a-center"><?php echo $this->__('Discount'); ?></th>
                            <th class="a-center"><?php echo $this->__('Row Total'); ?></th>
                            <th class="a-center"><?php echo $this->__('Status'); ?></th>
                        </tr>
                    <?php foreach($this->getOrder()->getAllItems() as $item): ?>
                        <tr>
                            <td><?php echo $item->getName().'<br><i>('.$item->getSku().')</i>'; ?></td>
                            <td class="a-center"><?php echo (int)$item->getqty_ordered(); ?></td>
                            <td class="a-center"><?php echo (int)($item->getqty_ordered() - $item->getqty_shipped()); ?></td>
                            <td class="a-center"><?php echo (int)$item->getqty_refunded(); ?></td>
                            <td class="a-center"><?php echo $this->getOrder()->formatPrice($item->getrow_total_incl_tax()); ?></td>
                            <td class="a-center"><?php echo $this->getOrder()->formatPrice($item->getdiscount_amount()); ?></td>
                            <td class="a-center"><?php echo $this->getOrder()->formatPrice($item->getrow_total_incl_tax() - $item->getdiscount_amount()); ?></td>
                            <td class="a-center"><?php echo $item->getStatus(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </td>
    </tr>    
    <tr>
      <td >
            <!-- Shipments -->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Invoices, Shipments and Credit memos'); ?></h4>
                </div>
                <div class="fieldset">
                    <?php foreach($this->getOrder()->getInvoiceCollection() as $invoice): ?>
                        <p>- <?php echo $this->getInvoicePDF($this->__('Invoice #%s (%s)', $invoice->getincrement_id(), $invoice->getcreated_at()), $invoice->getId()); ?></p>
                    <?php endforeach; ?>
                    <?php foreach($this->getOrder()->getShipmentsCollection() as $shipment): ?>
                        <p>- <?php echo $this->getShipmentPDF($this->__('Shipment #%s (%s)', $shipment->getincrement_id(), $shipment->getcreated_at()), $shipment->getId()); ?></p>
                        <?php foreach($shipment->getTracksCollection() as $tracking): ?>
                            <p> - <?php echo $this->__('Tracking #%s', $tracking->getnumber()); ?></p>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    <?php foreach($this->getOrder()->getCreditMemosCollection() as $creditmemo): ?>
                        <p>- <?php echo $this->getCreditMemoPDF($this->__('Credit memo #%s (%s)', $creditmemo->getincrement_id(), $creditmemo->getcreated_at()), $creditmemo->getId()); ?></p>
                    <?php endforeach; ?>
                </div>
            </div>
        </td>
        <td colspan="2" style="width: 450px">
            <!-- Comments -->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Comments'); ?></h4>
                </div>
                <div class="fieldset">
                    <?php foreach($this->getFullHistory($this->getOrder()) as $comments): ?>
                          <p>- <?php echo $comments['created_at'].' : <b>'.$comments['title'].'</b> <i>'.$comments['comment'].'</i>';
                          if($comments['notified']){
                            echo '('.$this->__('Notified').')';
                          }
                          ?>
                          </p>
                    <?php endforeach; ?>
                </div>
            </div>
        </td>
    </tr>
    
    
</table>


</div>