<h1><?php echo $this->getRmaLink(); ?></h1>

<table border="0" width="100%">    
   <tr>
        <td >
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Rma informations'); ?></h4>
                </div>
                <div class="fieldset">
                    <table border="0" width="100%">
                        <tr>
                            <td>
                                <p><?php echo $this->__('Date : %s', $this->getRma()->getrma_created_at()); ?></p>
                                <p><?php echo $this->__('Status : %s', $this->getRma()->getrma_status()); ?></p>
                                <p><?php echo $this->__('Order %s', $this->getRmaOrderLink()); ?></p>
                                <p><?php echo $this->__('Customer : %s', $this->getRmaCustomerLink()); ?></p>
                                <p><?php echo $this->__('Manager : %s', $this->getRmaManagerName()); ?></p>
                                <p><?php echo $this->__('Valid until %s', $this->getRma()->getrma_expire_date()); ?></p>
                            </td>
                            <td>
                                <p><?php echo '<b>'.$this->__('Private comment').'</b><br>'.$this->getRma()->getrma_private_description(); ?></p>
                                <p><?php echo '<br><b>'.$this->__('Public comment').'</b><br>'.$this->getRma()->getrma_public_description(); ?></p>
                            </td>
                        </tr>
                    </table>

                </div>
            </div>

            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Rma products'); ?></h4>
                </div>
                <div class="fieldset">
                     <table border="0" width="100%">
                        <tr>
                            <th><?php echo $this->__('Product'); ?></th>                            
                            <th class="a-center"><?php echo $this->__('Qty available'); ?></th>
                            <th class="a-center"><?php echo $this->__('Qty to return'); ?></th>
                            <th class="a-center"><?php echo $this->__('Reason'); ?></th>
                            <th class="a-center"><?php echo $this->__('Request Type'); ?></th>
                            <th class="a-center"><?php echo $this->__('Comment'); ?></th>
                            <th class="a-center"><?php echo $this->__('Serials'); ?></th>
                        </tr>
                    <?php foreach($this->getRma()->getProducts() as $item): ?>
                        <tr>
                            <td><?php echo $item->getrp_product_name(); ?></td>
                            <td class="a-center"><?php echo (int)$this->getAvailableQty($item); ?></td>
                            <td class="a-center"><?php echo (int)$item->getrp_qty(); ?></td>
                            <td class="a-center"><?php echo $item->getrp_reason(); ?></td>
                            <td class="a-center"><?php echo $item->getrp_request_type(); ?></td>
                            <td class="a-center"><?php echo $item->getrp_description(); ?></td>
                            <td class="a-center"><?php echo $item->getrp_serials(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </td>
    </tr>    
</table>

</div>