<?php
/** @var $this BurnOut_SupplierFeed_Block_Adminhtml_Feed_Edit_Renderer_Mapping */
?>
<?php
$feed = $this->getFeedModel();
$map = $feed->getFieldsMap();
$rows = $this->getExampleRows();
?>
<style>
    .grid {
        width: 100%;
        border: 1px solid #cbd3d4;
        border-bottom: none;
    }

    .grid td {
        border-width: 0 1px 1px 0;
        border-color: #dadfe0;
        border-style: solid;
    }
</style>
<?php if (!count($rows)): ?>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo Mage::helper('catalog')->__('Feed file not present. Please save the feed first'); ?>
                </li>
            </ul>
        </li>
    </ul>
<?php else: ?>
    <h4 style='color:#05a'><?php echo $this->__('Use preview to assign to each column a Magento attribute'); ?></h4>
    <br/>
    <?php $cols = $rows[0]; ?>
    <table class="data grid" cellspacing="0">
        <thead>
        <tr>
            <?php foreach ($cols as $k => $col): ?>
                <td class="input">
                    <input type='radio' id='key_field' name='settings[key_field]' value='<?php echo $k ?>'
                        <?php echo $feed->getSettingsValue('key_field') == $k ? ' checked' : '' ?> >
                    <?php echo $this->__('Use as key'); ?>
                </td>
            <?php endforeach; ?>
        </tr>
        <tr>
            <?php foreach ($cols as $k => $col): ?>
                <td class="input">
                    <select name='fields_map[]' id='attr_<?php echo $k ?>'>
                        <option value=0><?php echo $this->__('Select attribute'); ?></option>
                        <optgroup label="Stock/Warehouse">
                            <?php foreach ($this->getStockAttributes() as $code => $name): ?>
                                <option <?php echo isset($map[$k]) && $map[$k] == $code ? ' selected ' : ' '; ?>
                                    value='<?php echo $code ?>'><?php echo $name ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                        <optgroup label="Product Global Attributes">
                            <?php foreach ($this->getProductAttributes() as $code => $name): ?>
                                <option <?php echo isset($map[$k]) && $map[$k] == $code ? ' selected ' : ' '; ?>
                                    value='<?php echo $code ?>'><?php echo $name ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                    </select>
                </td>
            <?php endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($rows as $cols): ?>
            <tr <?php echo ($i % 2 == 0) ? ' class="even"' : '' ?> >
                <?php foreach ($cols as $value): ?>
                    <td class="a-center"><?php echo Mage::helper('core/string')->truncate($this->escapeHtml($value), '50'); ?></td>
                <?php endforeach; ?>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>

        <tr <?php echo ($i % 2 == 0) ? ' class="even"' : '' ?> >
            <?php foreach ($cols as $col): ?>
                <td class="last a-center">...</td>
            <?php endforeach; ?>
        </tr>
        </tbody>
    </table>
<?php endif; ?>


