<?php
/** @var $this BurnOut_SupplierFeed_Block_Adminhtml_Feed_Edit_Renderer_Rules */
?>
<style>
    .buttons_wrap {
        height: 22px;
        margin-bottom: 20px;
        clear: both;
    }

    .ruletable {
        width: 500px;
    }

    .ruletable tr td {
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #new_rule {
        border: 1px solid #cbd3d4;
        width: 720px;
    }

    .cell-behaviour, .cell-condition {
        font-weight: bold;
        text-align: center;
    }

    .operation {
        color: red;
        padding: 0 6px;
        text-align: center;
        font-weight: bold;
    }
</style>
<?php
$conditions = $this->getRuleConditions();
$behavior = $this->getRuleBehaviours();
$columns = $this->getCsvColumns();
?>
<?php if (!count($columns)): ?>
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>
                    <?php echo Mage::helper('catalog')->__('Feed file not present. Please save the feed first'); ?>
                </li>
            </ul>
        </li>
    </ul>
<?php else: ?>
    <div class="buttons_wrap">
        <button id="newRuleBtn" title='Add rule' type='button' class='scalable save add right'
                onclick='<?php echo $this->getJsObjectName() ?>.showNewRule()'>
            <span><span><span>Create New Rule</span></span></span>
        </button>
    </div>
    <table id="new_rule" class="no-display ruletable">
        <col width="1"/>
        <col width="1"/>
        <col/>
        <col/>
        <col/>
        <col/>
        <col/>
        <col/>
        <tbody>
        <tr id="new_rule_row">
            <td class="operation">IF</td>
            <td class="field_id">
                <select>
                    <option value='-1'>Choose field...</option>
                    <?php foreach ($columns as $k => $col): ?>
                        <option value='<?php echo $k ?>'><?php echo "[{$k}] - {$col}" ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td class="condition">
                <select>
                    <?php foreach ($conditions as $id => $label): ?>
                        <option value='<?php echo $id ?>'><?php echo $label ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td class="condition_value">
                <input style='width:45px;'>
            </td>
            <td class="operation">THEN</td>
            <td class="behaviour">
                <select id='behavior' onchange='<?php echo $this->getJsObjectName() ?>.showNewBValue(this)'>
                    <option value='-1'>Choose behavior...</option>
                    <?php foreach ($behavior as $id => $label): ?>
                        <option value='<?php echo $id ?>'><?php echo $label ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td class="behaviour_value">
                <input style='width:45px;'>
            </td>
            <td class="col-btn">
                <button title='Add rule' type='button' class='scalable save add'
                        onclick='<?php echo $this->getJsObjectName() ?>.addRule()'>
                    <span><span><span>Add Rule</span></span></span>
                </button>
            </td>
        </tr>
        </tbody>
    </table>

    <table cellspacing="0" class="data border ruletable" id="<?php echo $this->getHtmlId() ?>_grid" width="100%">
        <col width="1"/>
        <col/>
        <col width="1"/>
        <col/>
        <col/>
        <tbody id="<?php echo $this->getHtmlId() ?>_list">
        <?php if (!$this->hasRules()): ?>
            <tr id='noRule'>
                <td colspan="6"> No rule has been defined</td>
            </tr>
        <?php endif; ?>
        <tr id="<?php echo $this->getHtmlId() ?>_template" class="template no-display">
            <td class="operation">IF</td>
            <td class="cell-condition"><label></label></td>
            <td class="operation">THEN</td>
            <td class="cell-behaviour"><label></label></td>
            <td class="a-right last">
                <button type='button' class="scalable delete a-right"
                        onclick="<?php echo $this->getJsObjectName() ?>.removeRule('__id__')">
                    <span><span><span>Remove</span></span></span>
                </button>
            </td>
        </tr>
        </tbody>
    </table>
    <?php ?>
<?php endif; ?>
<input type="hidden" id="<?php echo $this->getHtmlId() ?>_save"
       name="rules_map"
       value='<?php echo $this->getRulesJson() ?>'/>
<script type="text/javascript">
    //<![CDATA[
    var <?php echo $this->getJsObjectName(); ?> =
    new Feed.Rules('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getJsonOptions() ?>', '<?php echo $this->getColumnJson() ?>');
    //]]>
</script>





