<p>
    <?php echo $this->getButtonsHtml('left') ?>
</p>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3
                    class="icon-head"><?php echo $this->_attributeName . ' ' . Mage::helper('burnout_shopby')->__('Pages') ?></h3>
            </td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml('right') ?>
        </tr>
    </table>
</div>
<?php if (!$this->isSingleStoreMode()): ?>
    <?php echo $this->getChildHtml('store_switcher'); ?>
<?php endif; ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>