<?php
/**
 * @var $this BurnOut_SupplierFeed_Block_Adminhtml_Feed_Edit_Tab_Products
 */
?>
<ul id="products_grid_tabs" class="tabs-horiz" style="margin-top:-20px">
    <!--    <li>-->
    <!--        <a href="#" id="new" name="top_tab" title="Show New Collection Products of this Supplier"-->
    <!--           onclick="switchTab(this)" class="tab-item-link active">-->
    <!--            </span>New Collection Products</span>-->
    <!--        </a>-->
    <!--    </li>-->
    <li>
        <a href="#" id="imported" name="top_tab" title="Currently Imported Products"
           onclick="switchTab(this)" class="tab-item-link active">
            <span>Imported</span>
        </a>
    </li>
    <li>
        <a href="#" id="feed" name="top_tab" title="Last Feed Matched Products"
           onclick="switchTab(this)" class="tab-item-link">
            <span>Last Feed</span>
        </a>
    </li>
    <li>
        <a href="#" id="missing" name="top_tab" title="Supplier Missing Products"
           onclick="switchTab(this)" class="tab-item-link">
            <span>Missing</span>
        </a>
    </li>
</ul>

    <p style="font-weight:bold;color:#06a;margin-bottom:20px;">
        These grids are updated at <?php echo Mage::registry('feed_data')->getFinishedAt() ?>
    </p>

    <div id="products_imported" name="products_tab">
        <?php echo $this->getLayout()->createBlock('burnout_supplierfeed/adminhtml_feed_edit_grid_imported')->setBlockName('importedProductGrid')->toHtml() ?>
    </div>

    <div id="products_feed" name="products_tab" style="display:none">
        <?php echo $this->getLayout()->createBlock('burnout_supplierfeed/adminhtml_feed_edit_grid_feed')->setBlockName('feedProductGrid')->toHtml() ?>
    </div>
<?php //if (count($ids = $feed->getProductIds())): ?>
    <div id="products_missing" name="products_tab" style="display:none">
        <?php echo $this->getLayout()->createBlock('burnout_supplierfeed/adminhtml_feed_edit_grid_missing')->setBlockName('missingProductGrid')->toHtml() ?>
    </div>
<?php //endif; ?>

    <script type="text/javascript">
        function switchTab(obj) {
            var dest = obj.id;
            var menutabs = document.getElementsByName('top_tab');
            var tabs = document.getElementsByName('products_tab');

            for (var i = 0; i < tabs.length; ++i) {
                tabs[i].style.display = "none";
                menutabs[i].className = "tab-item-link";
            }

            document.getElementById('products_' + dest).style.display = 'block';
            obj.className = "tab-item-link active";
        }
    </script>
