<?php
/**
 * @var $this BurnOut_SalesExtraFees_Block_Adminhtml_Sales_Order_Create_Totals_Abstract
 */
?>
<?php if ($this->displayBoth()): ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getExcludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getFeeExcludeTax()) ?>
        </td>
    </tr>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getIncludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getFeeIncludeTax()) ?>
        </td>
    </tr>
<?php elseif ($this->displayIncludeTax()) : ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getFeeIncludeTax()) ?>
        </td>
    </tr>
<?php else: ?>
    <tr>
        <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right">
            <?php echo $this->formatPrice($this->getFeeExcludeTax()) ?>
        </td>
    </tr>
<?php endif; ?>
