<head>
    <title>Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/style.css">
<!--    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">-->

    <script src="js/jquery/jquery-2.0.3.min.js"></script>
    <script src="js/player_new/build/mediaelement-and-player.js"></script>
    <script src="js/loader.js?v=1"></script>
    <script src="js/rai_player.js?v=1"></script>

    <!-- Add any other renderers you need; see Use Renderers for more information -->
    <link rel="stylesheet" href="js/player_new/src/css/mediaelementplayer.css"/>
</head>