<div id="product_supplier_association_popup_upper">
	<form id="form_associated_suppliers" name="form_associated_suppliers" enctype="multipart/form-data">
	    <button style="float:right; margin:5px 0;" type="button" onclick="SaveAssociatedSupplier()"><?php echo $this->__('Save') ?></button>
		<?php
			$block = $this->getLayout()->createBlock('Purchase/Product_Widget_SupplierTab');
			$block->setSupplier($this->getSupplier());
			$block->setProduct($this->getProduct());
			echo $html = $block->toHtml();
		?>
	</form>
</div>