<?php if ($this->getProduct()->isUniversal()): ?>
    <?php // we show nothing for universal product ?>
<?php else: ?>
    <style type="text/css">
        .part_box {
            margin-top: 40px;
        }

        .title_parts {
            font-size: 28px;
            font-weight: 400;
            text-align: center;
        }

        .table_zebra {
            width: 100%;
            margin: 10px 0;
            border-collapse: collapse;
        }

        .table_zebra th {
            border-bottom: 1px solid rgba(0, 0, 0, 0.06);
            font-size: 24px;
            font-weight: 400;
            padding: 2% 2%;
            line-height: 1.2222em;
            text-align: center;
        }

        .table_zebra .odd {
            background: #fbfbfb;
        }

        .table_zebra tbody > tr:hover {
            color: #3ec2df;
            background-color: rgba(0, 0, 0, 0.03);
        }

        .table_zebra td {
            padding: 2% 2%;
            text-align: center;
        }

        .table_zebra tbody > tr:hover {
            color: #3ec2df;
            background-color: rgba(0, 0, 0, 0.03);
        }
    </style>
    <div class="part_box">
        <div class="title_parts">
            <span><?php echo $this->__('This part is compatible with these motocycles') ?></span>
        </div>
        <table class="table_zebra" summary="Compatibility">
            <thead>
            <tr>
                <th scope="col"><?php echo $this->__('Make') ?></th>
                <th scope="col"><?php echo $this->__('Model') ?></th>
                <th scope="col"><?php echo $this->__('Year') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 0; ?>
            <?php foreach ($this->getParts() as $part): ?>
                <tr class="<?php echo($i % 2 ? '' : 'odd') ?>">
                    <td><?php echo $part->getMake() ?></td>
                    <td><?php echo $part->getModelCcmSubmodel() ?></td>
                    <td><?php echo $part->getYear() ?></td>
                </tr>
                <?php $i++; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>

