<div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none" id="mySidebar">
    <button class="w3-bar-item w3-button w3-large"
            onclick="w3_close()">Close &times;
    </button>
    <a href="#" class="w3-bar-item w3-button">Link 1</a>
    <a href="#" class="w3-bar-item w3-button">Link 2</a>
    <a href="#" class="w3-bar-item w3-button">Link 3</a>
</div>


<div id="main" class="w3-main">

    <div class="w3-teal">
        <button id="openNav" class="w3-button w3-teal w3-xlarge" onclick="w3_open()">&#9776;</button>
        <div class="w3-container">
            <h1>My Page</h1>
        </div>
    </div>

    <div class="w3-container w3-sand w3-hover-border-deep-purple">
        <div class="w3-panel w3-center">
            <div class="w3-card-4 w3-light-gray card-box">

                <header class="w3-container w3-black">
                    <h5>Header</h5>
                </header>

                <div class="w3-container">
                    <p>
                        <canvas id="myChart" width="400" height="400"></canvas>
                    </p>
                    <script>
                        var myChart = new Chart(jQuery('#myChart'), JSON.parse('<?php echo $this->getJsonConfig()?>'));

                        myChart.canvas.parentNode.style.width = '580px';
                        // myChart.canvas.parentNode.style.heigth = '320px';
                    </script>
                </div>

                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>

            </div>
            <div class="w3-card-4 w3-light-gray card-box">

                <header class="w3-container w3-black">
                    <h5>Header</h5>
                </header>

                <div class="w3-container">
                    <p>
                        <canvas id="myChart2" width="400" height="400"></canvas>
                    </p>
                    <script>
                        var myChart2 = new Chart(jQuery('#myChart2'), JSON.parse('<?php echo $this->getJsonConfig()?>'));

                        myChart2.canvas.parentNode.style.width = '580px';
                        // myChart2.canvas.parentNode.style.heigth = '320px';
                    </script>
                </div>

                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>

            </div>
        </div>
        <div class="w3-panel w3-center">

            <div class="card-box w3-card-4 w3-light-gray">
                <header class="w3-container w3-black">
                    <h6>TEST INPUT</h6>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">
                    </form>
                    </p>
                </div>
                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4 w3-light-gray card-box">
                <header class="w3-container w3-black">
                    <h6>TEST INPUT 2</h6>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4 w3-light-gray card-box">
                <header class="w3-container w3-black">
                    <h6>TEST INPUT</h6>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4 w3-light-gray card-box">
                <header class="w3-container w3-black">
                    <h6>TEST INPUT 2</h6>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container">
                    <h5>Footer</h5>
                </footer>
            </div>

        </div>

    </div>
</div>

<script>
    function w3_open() {
        document.getElementById("main").style.marginLeft = "25%";
        document.getElementById("mySidebar").style.width = "25%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
    }

    function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
    }
</script>

