
<div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none" id="mySidebar">
    <button class="w3-bar-item w3-button w3-large"
            onclick="w3_close()">Close &times;
    </button>
    <a href="#" class="w3-bar-item w3-button">Link 1</a>
    <a href="#" class="w3-bar-item w3-button">Link 2</a>
    <a href="#" class="w3-bar-item w3-button">Link 3</a>
</div>


<div id="main" class="w3-main">

    <div class="w3-teal">
        <button id="openNav" class="w3-button w3-teal w3-xlarge" onclick="w3_open()">&#9776;</button>
        <div class="w3-container">
            <h1>My Page</h1>
        </div>
    </div>

    <div class="w3-container w3-sand">
        <div class="w3-panel">
            <div class="w3-card-4" style="display: inline-block">
                <header class="w3-container w3-blue">
                    <h1>TEST INPUT</h1>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4" style="display: inline-block">
                <header class="w3-container w3-blue">
                    <h1>TEST INPUT 2</h1>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4" style="display: inline-block">
                <header class="w3-container w3-blue">
                    <h1>TEST INPUT</h1>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Footer</h5>
                </footer>
            </div>
            <div class="w3-card-4" style="display: inline-block">
                <header class="w3-container w3-blue">
                    <h1>TEST INPUT 2</h1>
                </header>
                <div class="w3-container">
                    <p>
                    <form class="w3-container">
                        <label>First Name</label>
                        <input class="w3-input" type="text" pattern="[\p{Letter}\p{White_Space}]+">

                        <label>Last Namel</label>
                        <input class="w3-input" type="text">

                    </form>
                    </p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Footer</h5>
                </footer>
            </div>

        </div>
        <div class="w3-panel">
            <div class="w3-card-4" style="display: inline-block">

                <header class="w3-container w3-blue">
                    <h1>Header</h1>
                </header>

                <div class="w3-container">
                    <p>
                        <canvas id="myChart" width="400" height="400"></canvas>
                    </p>
                </div>

                <footer class="w3-container w3-blue">
                    <h5>Footer</h5>
                </footer>

            </div>
        </div>
    </div>
</div>

<script>
    function w3_open() {
        document.getElementById("main").style.marginLeft = "25%";
        document.getElementById("mySidebar").style.width = "25%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
    }

    function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
    }
</script>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [
                "Red",
                "Blue",
                "Yellow",
                "Green",
                "Purple",
                "Orange"
            ],
            datasets: [{
                label: '# of Votes',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

    myChart.canvas.parentNode.style.width = '640px';
    myChart.canvas.parentNode.style.heigth = '480px';
</script>