<div id="app">
    <div class="w3-container w3-amber">
        <h3>{{ch_current.title}}</h3>
    </div>

    <div class="content">
        <?php Mage::app()->getBlockHtml('page/header') ?>
        <?php Mage::app()->getBlockHtml('page/player') ?>

        <div class="w3-bar w3-mobile w3-border w3-round channel_list">
            <?php Mage::app()->getBlockHtml('page/channel') ?>
        </div>

        <?php Mage::app()->getBlockHtml('page/program') ?>

    </div>

</div>

<script>
    <?php $rai = new Video_Rai() ?>
    var data = JSON.parse('<?php echo $rai->getJsonConfig() ?>');
    var vm = new Vue({
        data: data,
    });

    vm.$mount('#app');


    var player = new MediaElementPlayer('videoElement', {
        /**
         * YOU MUST SET THE TYPE WHEN NO SRC IS PROVIDED AT INITIALISATION
         * (This one is not very well documented.. If one leaves the type out, the success event will never fire!!)
         **/
        type: ["video/mp4"],
        features: ['playpause', 'progress', 'current', 'duration', 'tracks', 'volume'],
        mediaElementInitialized: false,
        //more options here..

        success: function (mediaElement, domObject) {
            this.mediaElementInitialized = true;
        },
        error: function (e) {
            alert(e);
        }
    });

</script>


</body>
</html>