<div id="app">

    <div class="w3-container w3-black">
        <h3>{{ch_current.title}}</h3>
    </div>

    <template id="player">
        <div class="w3-container w3-black">
            <div style="margin: 0% 12%">
                <!--        <img src="img/tv.png" alt="Rai Tv" style="max-width: 100%">-->
                <video id="videoElement" style="max-width: 100%" :src="src_current"/>
            </div>
        </div>
    </template>

    <div class="w3-bar w3-mobile w3-border w3-round channel_list">
        <channels inline-template v-for="(channel, index) in channels"
                  :id="index"
                  :channel="channel">
            <a class="w3-bar-item w3-button" :id="id" @click="click">{{channel.title}}</a>
        </channels>
    </div>

    <template id="daylist">
        <div class="w3-container day" v-for="day in days" :day="day">
            <header class="w3-container w3-blue">
                <h1>{{day}}</h1>
            </header>
            <button-counter></button-counter>
            <program></program>
        </div>
    </template>

</div>

<script>
    var data = JSON.parse('<?php echo $this->getJsonConfig() ?>');
    var vuePlayer = new Vue({
        data: data,
        // beforeMount: function () {
        //
        // },
        // created: function () {
        //
        // },
        mounted: function () {
            this.player = new MediaElementPlayer('videoElement', {
                /**
                 * YOU MUST SET THE TYPE WHEN NO SRC IS PROVIDED AT INITIALISATION
                 * (This one is not very well documented.. If one leaves the type out, the success event will never fire!!)
                 **/
                type: ["video/mp4"],
                features: ['playpause', 'progress', 'current', 'duration', 'tracks', 'volume'],
                mediaElementInitialized: false,
                //more options here..

                success: function (mediaElement, domObject) {
                    this.mediaElementInitialized = true;
                },
                error: function (e) {
                    alert(e);
                },
            });
        },

    });

    vuePlayer.$mount('#app');



</script>
