
<form id="supplier_invoice_edit_form" name="supplier_invoice_edit_form"  enctype= "multipart/form-data" method="POST" action="<?php echo $this->getSaveUrl()?>">
<?php $block = $this->getLayout()->createBlock('paymentmanagement/adminhtml_tabs');
echo $block->toHtml();?>
</form>
<style type="text/css">
    #purchase_invoices_creditmemos_tabs{position:relative;}
    #purchase_invoices_creditmemos_tabs li{ float:left;}
    #purchase_invoices_creditmemos_tabs li a.tab-item-link.active + div{ display:block!important; position:absolute; top:70px; width:95%; left:0; padding:15px;}
    #purchase_invoices_creditmemos_tabs li a.tab-item-link{ background: #e2e2e2; border-color: #cccccc; border-style: solid; border-width: 1px; display: block; float: left; margin: 5px; padding: 5px; text-align: center; width: 100px; min-height:35px;line-height:35px;}
    #purchase_invoices_creditmemos_tabs li a.tab-item-link span{background:none; min-height:35px;padding:0;}
    #purchase_invoices_creditmemos_tabs li a.tab-item-link.active{ background: #ffffff; border-color: #cccccc #cccccc #ffffff; border-style: solid; border-width: 1px; display: block; float: left; margin: 5px; padding: 5px; text-align: center; width: 100px; min-height:35px;}
    #purchase_invoices_creditmemos_tabs_invoices_creditmemos{width: 150px!important;}
</style>