<div class="entry-edit">
    <?php if($this->getCurrentSupplierInvoiceData("psi_type") =="invoice"){ ?>
    <h3><?php echo$this->__('Supplier Invoice for #%s', $this->getOrder()->getpo_order_id())?></h3>
    <?php }elseif($this->getCurrentSupplierInvoiceData("psi_type") == "creditmemo") { ?>
    <h3><?php echo$this->__('Supplier Credit Memo for #%s', $this->getOrder()->getpo_order_id())?></h3>
    <?php }else{ ?>
    <h3><?php echo$this->__('Supplier Invoice or credit memo for #%s', $this->getOrder()->getpo_order_id())?></h3>
    <?php } ?>
    <br/>
        <table cellspacing="5" cellpadding="10" class="grid-header">
            <tr>
                <td class="label"><?php echo $this->__('Reference Id'); ?></td>
                <td class="input-ele"><input type="text" size="40" name="psi_invoice_id" id="psi_invoice_id" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_invoice_id"); ?>"></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Total excl tax'); ?></td>
                <td class="input-ele">
                    <input type="text" size="40" name="psi_amount" id="psi_amount" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_amount"); ?>">
                    <?php echo mage::helper('purchase/SupplierInvoice')->getInvoiceCurrencySymbol($this->getOrder()); ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Type'); ?></td>
                <td class="input-ele">
                    <?php echo $this->getInvoiceType('psi_type',$this->getCurrentSupplierInvoiceData("psi_type")); ?>
                </td>
            </tr>

            <tr>
                <td class="label"><?php echo $this->__('Tax Rate'); ?></td>
                <td class="input-ele">
                    <?php echo $this->getTax('psi_tax_rate_id',$this->getCurrentSupplierInvoiceData("psi_tax_rate_id")?$this->getCurrentSupplierInvoiceData("psi_tax_rate_id"):0); ?>
                </td>
            </tr>

            <tr>
                <td class="label"><?php echo $this->__('Tax amount'); ?></td>
                <td class="input-ele">
                    <input type="text" id="psi_tax_amount" name="psi_tax_amount" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_tax_amount"); ?>">
                </td>
            </tr>
            
            <tr>
                <td class="label"><?php echo $this->__('Date'); ?></td>
                <td class="input-ele"><input type="date" name="psi_date" id="psi_date" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_date"); ?>"></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Due date'); ?></td>
                <td class="input-ele"><input type="date" name="psi_due_date" id="psi_due_date" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_due_date"); ?>"></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Payment date'); ?></td>
                <td class="input-ele"><input type="date" name="psi_payment_date" id="psi_payment_date" value="<?php echo $this->getCurrentSupplierInvoiceData("psi_payment_date"); ?>"></td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Status'); ?></td>
                <td class="input-ele">
                    <?php echo $this->getStatusCombo("psi_status",$this->getCurrentSupplierInvoiceData("psi_status")); ?>
                </td>
            </tr>
            <?php if($this->getCurrentSupplierInvoiceData("psi_attachment")) : ?>
            <tr>
                <td class="label"><?php echo $this->__('Attachments'); ?></td>
                <td class="input-ele">
                    <?php
                        $imageDownloadUrl = Mage::getDesign()->getSkinUrl('images/icon_export.png');
                        $urlDownlaod = $this->getUrl('adminhtml/Purchase_SupplierInvoice/DownloadAttachment', array('psi_id' => $this->getCurrentSupplierInvoiceId()));
                        echo '<a href="'.$urlDownlaod.'" alt="'.$this->__('Downlaod').'"><img src="' . $imageDownloadUrl . '"></a>';

                    if(Mage::getSingleton('admin/session')->isAllowed('admin/erp/purchasing/supplier_invoices/delete')) {
                        $imageDeleteUrl = Mage::getDesign()->getSkinUrl('images/cancel_icon.gif');
                        $urlDelete = $this->getUrl('adminhtml/Purchase_SupplierInvoice/DeleteAttachment', array('psi_id' => $this->getCurrentSupplierInvoiceId()));
                        echo '&nbsp&nbsp&nbsp<a href="' . $urlDelete . '"alt="'.$this->__('Delete').'"><img src="' . $imageDeleteUrl . '"></a>';
                    }
                    ?>
                </td>
            </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><?php echo $this->__('Add Attachment'); ?></td>
                <td class="input-ele">
                    <input type="file" name="psi_attachment" id="psi_attachment">
                </td>
            </tr>
            <tr>
                <td class="label"><?php echo $this->__('Notes'); ?></td>
                <td class="input-ele">
                    <textarea id="psi_notes" name="psi_notes" cols="50" rows="5"><?php echo $this->getCurrentSupplierInvoiceData("psi_notes"); ?></textarea>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <input type="hidden" name="psi_po_id" id="psi_po_id" value="<?php echo $this->getPurchaseOrderId();  ?>">
                    <input type="hidden" name="psi_id" id="psi_id" value="<?php echo $this->getCurrentSupplierInvoiceId(); ?>">
                    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
                </td>

                <td class="input-ele"><button onclick="document.getElementById('supplier_invoice_edit_form').submit();" type="button"><span><?php echo $this->__('Save')?></span></button></td>
            </tr>
        </table>
</div>
