<br/><br/>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Create a new dummy row')?></h3></td>
            <td align="right">
                <button onclick="submitDummyProduct()" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="dummy_product_form" name="dummy_product_form" action="<?php echo $this->getUrl('*/*/DummyProductsSave')?>">
    
    <input type="hidden" id="pop_order_num" name="pop_order_num" value="<?php echo $this->getOrderId()?>"/>

    <div class="entry-edit">
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Sku'); ?></td>
                    <td class="input-ele"><input class="required-entry" type="text" id="" name="pop_product_sku"/></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Name'); ?></td>
                    <td class="input-ele"><input class="required-entry" type="text" id="" name="pop_product_name"/></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Qty'); ?></td>
                    <td class="input-ele"><input class="required-entry validate-number" type="text" id="" name="pop_qty"/></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Tax rate'); ?></td>
                    <td class="input-ele"><input class="required-entry validate-number" type="text" id="" name="pop_tax_rate"/></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Unit Price'); ?></td>
                    <td class="input-ele"><input class="required-entry validate-number" type="text" id="" name="pop_price_ht"/></td>
                </tr>
            </table>
        </fieldset>
    </div>
</form>
