<?php if($this->isAutoSaveEnabled()): ?>
    <script>
        var ticketAutoSave = new autoSave('<?php echo $this->getAutoSaveRate(); ?>', '<?php echo $this->isAutoSaveEnabled(); ?>');

        setInterval(function () {

            //WYSIWIG/tinyMCE
            if(document.getElementsByClassName("mceEditor").length >0) {
                var lastTinyMceLength = ticketAutoSave.tinyMCELength;
                ticketAutoSave.tinyMCELength = tinyMCE.get('ctm_content').getContent().length;
                if(lastTinyMceLength != ticketAutoSave.tinyMCELength) {
                    ticketAutoSave.tick = 0;
                }
            }

            if(ticketAutoSave.tick>=0) {
                ticketAutoSave.tick++;
            }
            console.log('tick='+ticketAutoSave.tick);


            ticketAutoSave.saveTicket();
        }, 1000);

        //global windows event
        window.addEventListener("click", ticketAutoSave.reset, false);
        window.addEventListener("keypress", ticketAutoSave.reset, false);
        window.addEventListener("keyup", ticketAutoSave.reset, false);
        window.addEventListener("mousemove", ticketAutoSave.reset, false);

    </script>
<?php endif; ?>