 <div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td>
                <h3><?php echo $this->getTitle(); ?></h3>                   
            </td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl() ?>'" class="scalable back" type="button"><span><?php echo $this->__('Back') ?></span></button>
                <?php if ($this->getTicket()->getId()): ?>
                    <button onclick="if (confirm('<?php echo $this->__('Are you sure to delete this ticket ?'); ?>')) {document.location.href='<?php echo $this->getDeleteUrl($this->getTicket()->getct_id()) ?>';}" class="scalable delete" type="button"><span><?php echo $this->__('Delete') ?></span></button>
                    <button onclick="document.location.href='<?php echo $this->getNotifyAdminUrl() ?>'" class="scalable" type="button"><span><?php echo $this->__('Notify admin') ?></span></button>
                    <button onclick="document.location.href='<?php echo $this->getNotifyCustomerUrl() ?>'" class="scalable" type="button"><span><?php echo $this->__('Notify customer') ?></span></button>
                <?php endif; ?>
                <?php if ($this->getTicket()->getCustomer()): ?>
                    <button onclick="document.location.href='<?php echo $this->getNewTicketUrl($this->getTicket()->getCustomer()->getId()) ?>'" class="scalable" type="button"><span><?php echo $this->__('New ticket') ?></span></button>                
                    <button onclick="document.location.href='<?php echo $this->getSetSenderAsSpammerUrl($this->getTicket()->getCustomer()->getEmail()) ?>'" class="scalable" type="button"><span><?php echo $this->__('Spam') ?></span></button>
                <?php endif; ?>
                <button onclick="editForm.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save') ?></span></button>
            </td>
        </tr>
    </table>
</div>
