<?php $lastMessageId=0; ?>

<?php foreach ($this->getTicket()->getMessages() as $message) : ?>

    <?php $lastMessageId = ($message->getId()>$lastMessageId)?$message->getId():$lastMessageId; ?>

    <div class="box message-<?php echo $message->getCssStyle(); ?>">
        <table cellspacing="0" width="100%">
            <tr>
                <td>
                    <p style="margin-bottom: 15px;"><b><?php echo $message->getBackofficeMessageHeader(); ?></b>"></a></p>
                </td>
                <td align="right">
                    <button class="scalable edit_message" name="edit_messages[<?php echo $message->getId(); ?>]" 
                            id="edit_messages[<?php echo $message->getId(); ?>]" type="button"
                            onclick="window.open('<?php echo $this->getUrl('adminhtml/CrmTicket_Ticket/EditMessage', array('ticket_id' => $this->getTicket()->getct_id(), 'message_id' => $message->getctm_id())); ?>')">
                            <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    </button>
                    <button class="scalable" name="edit_messages[<?php echo $message->getId(); ?>]"
                            id="print_messages[<?php echo $message->getId(); ?>]" type="button"
                            onclick="window.open('<?php echo $this->getUrl('adminhtml/CrmTicket_Ticket/PrintMessage', array('message_id' => $message->getctm_id())); ?>')">
                            <span><?php echo $this->__('Print'); ?></span>
                    </button>
                    <button class="scalable delete_message" name="delete_messages[<?php echo $message->getId(); ?>]"
                            id="delete_messages[<?php echo $message->getId(); ?>]" type="button"
                            onclick="deleteMessageAjax('<?php echo $this->getDeleteMessageUrl($message->getctm_id()); ?>');">
                            <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    </button>
                </td>
            </tr>
        </table>
        <div class="box-content crm_mess_box">
            <p><?php echo $message->getMessageBodyForHtmlDisplay(); ?></p>
        </div>
       <?php if (Mage::getStoreConfig('crmticket/attachements/allow_attachement_on_message')): ?>
        <?php $messageAttachements = $message->getAttachments(); ?>
        <?php if(count($messageAttachements)>0) :?>
           <div class="box-attachements">
               <p><hr/><br/><b><?php echo $this->__('Attachments : '); ?></b></p>
               <p>
               <?php foreach ($messageAttachements as $attachment): ?>
                   <div class="crm-attachment">
                       <?php
                       $attFileName=$attachment->getFileName();
                       if($attachment->canPreview()): ?>
                         <a href="#M-<?php echo $message->getId(); ?>" onclick="showImageAttachementPopup('<?php echo $this->getAttachmentMessageDownloadLink($message,$attachment); ?>','<?php echo $attFileName; ?>')"><?php echo $attFileName; ?></a>
                       <?php else: ?>
                         <a href="<?php echo $this->getAttachmentMessageDownloadLink($message,$attachment); ?>"><?php echo $attFileName; ?></a>
                        <?php endif; ?>
                         &nbsp;<a href="<?php echo $this->getAttachmentMessageDeleteLink($message, $attachment); ?>"><img src="<?php echo $this->getSkinUrl('images/cancel_icon.gif') ?>" /></a>
                   </div>
               <?php endforeach; ?>
               </p>
           </div>
        <?php endif; ?>
       <?php endif; ?>
    </div>
<?php endforeach; ?>

<input type="hidden" name="last_message_id" id="last_message_id" value="<?php echo $lastMessageId; ?>" />



