<?php /* ------------------------------------ MESSAGE FORM ------------------------------------  */ ?>
<div id="message_block">
  <div class="entry-edit-head collapseable">
      <a href="#" name="message_link" onclick="javascript:hideDisplayBlock(this, 'message_fieldset');" class="open" ><?php echo $this->__('New message'); ?></a>
  </div>
  <div id="message_fieldset" class="fieldset" style="display: block;">
      <div class="hor-scroll">
            <table class="form-list">
              <tbody>
                  <tr>
                      <td colspan="6">
                          <?php echo $this->getNewMessageEditor(); ?>
                      </td>
                  </tr>
                  <tr>
                        <td colspan="3">
                          <?php if (Mage::getStoreConfig('crmticket/attachements/allow_attachement_on_message')): ?>

                              <?php foreach ($this->getAttachments() as $attachment): ?>
                              <div class="crm-attachment">
                                  <?php
                                  $attFileName=$attachment->getFileName();
                                  if($attachment->canPreview()): ?>
                                    <a href="#" onclick="showImageAttachementPopup('<?php echo $this->getAttachmentDownloadLink($attachment); ?>','<?php echo $attFileName; ?>')"><?php echo $attFileName; ?></a>
                                  <?php else: ?>
                                    <a href="<?php echo $this->getAttachmentDownloadLink($attachment); ?>"><?php echo $attFileName; ?></a>
                                   <?php endif; ?>
                                    &nbsp;<a href="<?php echo $this->getAttachmentDeleteLink($attachment); ?>"><img src="<?php echo $this->getSkinUrl('images/cancel_icon.gif') ?>" /></a>
                              </div>
                              <?php endforeach; ?>

                              <?php $max = Mage::helper('CrmTicket/Attachment')->getAdminMaxAttachementAllowed();
                              $key = Mage::helper('CrmTicket/Attachment')->getAdminMessageAttachementKey();
                              for ($i = 1; $i <= $max; $i++): ?>
                              <input type="file" name="<?php echo $key.$i; ?>" id="<?php echo $key.$i; ?>"><br/>
                              <?php endfor; ?>
                         <?php endif; ?>
                        </td>                        
                        <td colspan="1">
                            <input type="hidden" name="send_email" id="send_email"  value="0"/>
                            <a href="#" name="option_link" onclick="javascript:hideDisplayBlock(this, 'message_options');" ><?php echo $this->__('Options'); ?></a>
                        </td>
                        <td colspan="2" class="send_message_button_container">                          
                            <button onclick="javascript:postNewMessage();" class="send_message_button" id="send_message_button" type="button"><span><?php echo $this->__('Send message'); ?></span></button>
                        </td>
                   </tr>
              </tbody>
          </table>

          <div id="message_options" style="display: <?php echo $this->isOptionMessageZoneIsOpen();?>">
          <table class="form-list">
              <tbody>
                  <tr>
                  <?php  if (Mage::getStoreConfig('crmticket/ticket_data/change_message_type')): ?>
                      <td class="label"><?php echo $this->__('Type'); ?></td>
                      <td class="value" colspan="5">
                          <select name="new_message[ctm_source_type]" id="ctm_source_type">
                              <?php foreach (mage::getModel('CrmTicket/Message')->getSourceTypes() as $k => $v): ?>
                                  <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                              <?php endforeach; ?>
                          </select>
                      </td>
                  <?php else: ?>
                      <td colspan="2"><input type="hidden" name="new_message[ctm_source_type]" id="ctm_source_type" value="<?php echo MDN_CrmTicket_Model_Message::TYPE_MAIL; ?>"></td>
                  <?php endif; ?>
                  </tr>
                  <tr>
                  <?php  if (Mage::getStoreConfig('crmticket/ticket_data/change_author')): ?>
                      <td class="label"><?php echo $this->__('Author'); ?></td>
                      <td class="value" colspan="5">
                          <select name="new_message[ctm_author]" id="ctm_author">
                              <?php foreach (mage::getModel('CrmTicket/Message')->getAuthors() as $k => $v): ?>
                                  <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                              <?php endforeach; ?>
                          </select>
                      </td>
                  <?php else: ?>
                      <td colspan="2"><input type="hidden" name="new_message[ctm_author]" id="ctm_author" value="<?php echo MDN_CrmTicket_Model_Message::AUTHOR_ADMIN; ?>"></td>
                  <?php endif; ?>
                  </tr>
                  <tr>
                      <td class="label"><?php echo $this->__('Default replies'); ?></td>
                      <td class="value" colspan="5">
                          <select id="default_reply" onchange="javascript:setDefaultReplyInCurrentMessage(this.value); ">
                              <option></option>
                              <?php foreach ($this->getDefaultReplies() as $reply): ?>
                                  <option value="<?php echo $reply->getFormattedContent(); ?>"><?php echo $reply->getcdr_name(); ?></option>
                              <?php endforeach; ?>
                          </select>
                      </td>
                  </tr>
              </tbody>
            </table>
          </div>
      </div>
  </div>
</div>
