<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Associated Customer Order for Drop Shipping')?></h4>
    </div>

    <div class="fieldset">
        <fieldset id="my-fieldset">
            <table cellspacing="10">
                <tr>
                    <th> <?php echo mage::helper('DropShipping')->__('Customer Order'); ?></th>
                    <th> <?php echo mage::helper('DropShipping')->__('Customer name'); ?></th>
                    <th> <?php echo mage::helper('DropShipping')->__('Customer e-mail'); ?></th>
                    <th> <?php echo mage::helper('DropShipping')->__('Billing address'); ?></th>
                    <th> <?php echo mage::helper('DropShipping')->__('Shipping address'); ?></th>
                </tr>
                <tr>
                    <td> <?php
                        $order = $this->getDropShippingSalesOrder();
                        $url = Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view', array('order_id' => $order->getId()));
                        echo '<a href="'.$url.'"  target="_blank">'.$order->getincrement_id().'</a>';
                        ?>
                    </td>
                    <td> <?php echo $this->getCustomerName(); ?></td>
                    <td> <?php echo $this->getCustomerEmail(); ?></td>
                    <td> <?php echo $this->getCustomerBillingAddress(); ?></td>
                    <td> <?php echo $this->getCustomerShippingAddress(); ?></td>
                </tr>
            </table>
        </fieldset>
    </div>

</div>