<!DOCTYPE html>

<html>
<head>
    <title>Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/style.css">
    <!--    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">-->

    <script src="js/jquery-2.0.3.min.js"></script>
    <script src="js/player/build/mediaelement-and-player.js"></script>

    <!-- Add any other renderers you need; see Use Renderers for more information -->
    <link rel="stylesheet" href="js/player/src/css/mediaelementplayer.css"/>

    <!-- data-main attribute tells require.js to load
                 scripts/main.js after require.js loads. -->
    <!--    <script data-main="scripts/main" src="scripts/require.js"></script>-->

    <script src="js/vue/vue.js"></script>
    <script src="js/vue/app.js"></script>
</head>

<body>
<div id="app">

    <div class="content">
        <header>
            <?php Vue::app()->getBlockHtml('page/header') ?>
            <?php Vue::app()->getBlockHtml('page/video') ?>

            <div class="w3-bar w3-mobile w3-border w3-round channel_list">
                <?php Vue::app()->getBlockHtml('page/channel') ?>
            </div>

        </header>
        <article>
            <?php Vue::app()->getBlockHtml('page/days') ?>
        </article>

    </div>


</div>

<script>
    <?php $rai = new Video_Rai() ?>
    var data = JSON.parse('<?php echo $rai->getJsonConfig() ?>');

    var vm = new Vue({
        data: data,
        beforeMount: function () {
            this.loadChannels();
            this.selectCh(1);
        },
        methods: {
            loadChannels: function () {
                for (var c in this.channel) {
                    for (var i in this.days) {
                        this.loadDayChannel(this.channel[c].id, this.days[i]);
                    }
                }
            },
            loadDayChannel: function (ch_id, day) {
                var channel = this.getChById(ch_id);
                var title = channel.title;
                $.ajax({
                    url: './ajax.php',
                    method: 'POST',
                    data: {day: day, ch: title},
                    success: function (data) {
                        var days = channel.days;
                        days.push({title: day, programs: JSON.parse(data)});
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            },

            selectCh: function (ch_id) {
                var ch = this.getChById(ch_id);
                this.ch_current = ch;
            },

            getChById: function (ch_id) {
                var i;
                for (i in this.channels) {
                    if (this.channels[i].id == ch_id) {
                        return this.channels[i];
                    }
                }
            },
        },
        created() {channels
            var self = this;
            this.$on('SwitchChannel', ch_id => {
                this.selectCh(ch_id);
                console.log(ch_id);
            });
        }
    });
    vm.$mount('#app');


    var player = new MediaElementPlayer('videoElement', {
        /**
         * YOU MUST SET THE TYPE WHEN NO SRC IS PROVIDED AT INITIALISATION
         * (This one is not very well documented.. If one leaves the type out, the success event will never fire!!)
         **/
        type: ["video/mp4"],
        features: ['playpause', 'progress', 'current', 'duration', 'tracks', 'volume'],
        mediaElementInitialized: false,
        //more options here..

        success: function (mediaElement, domObject) {
            this.mediaElementInitialized = true;
        },
        error: function (e) {
            alert(e);
        }
    });

</script>


</body>
</html>