

<table class="kpi_table">
    <tr>
        <th><?php echo $this->__('Payment status'); ?></th>
        <th><?php echo $this->__('Invoice total'); ?></th>
        <th><?php echo $this->__('Total paid'); ?></th>
        <th><?php echo $this->__('Balance due'); ?></th>
    </tr>
    <tr>
        <td><?php echo $this->getPaymentStatus(); ?></td>
        <td><?php echo $this->getSupplierInvoice()->getCurrency()->formatTxt($this->getSupplierInvoice()->getpsi_amount()); ?></td>
        <td><?php echo $this->getSupplierInvoice()->getCurrency()->formatTxt($this->getSupplierInvoice()->getpsi_total_paid()); ?></td>
        <td><?php echo $this->getBalanceDue(); ?></td>
    </tr>
</table>

<p>&nbsp;</p>


<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo$this->__('Register a new payment')?></h4>
    </div>
    <fieldset id="my-fieldset">
        <center>
                <div class="grid">
                    <table cellspacing="0" class="data">
                        <thead>
                        <tr class="headings">
                            <th class="a-center"><?php echo $this->__('Method'); ?></th>
                            <th class="a-center"><?php echo $this->__('Amount'); ?> (<?php echo $this->getSupplierInvoice()->getCurrency()->getcurrency_code(); ?>)</th>
                            <?php if ($this->getSupplierInvoice()->getCurrency()->getcurrency_code() != Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE)): ?>
                                <th class="a-center"><?php echo $this->__('Amount'); ?> (<?php echo Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE); ?>)</th>
                            <?php endif; ?>
                            <th class="a-center"><?php echo $this->__('Date'); ?></th>
                            <th class="a-center"><?php echo $this->__('Notes'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td align="center">
                                <select name="newpayment[psip_method]">
                                    <option></option>
                                    <?php foreach($this->getMethods() as $method): ?>
                                        <option value="<?php echo $method; ?>"><?php echo $method; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                            <td align="center">
                                <input type="text" name="newpayment[psip_amount]" value="<?php echo $this->getSupplierInvoice()->getBalanceDue(); ?>">
                            </td>
                            <?php if ($this->getSupplierInvoice()->getCurrency()->getcurrency_code() != Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE)): ?>
                                <td align="center">
                                    <input type="text" name="newpayment[psip_amount_base]">
                                </td>
                            <?php endif; ?>
                            <td align="center">
                                <input type="text" id="newpayment[psip_date]" name="newpayment[psip_date]" value="<?php echo date('Y-m-d'); ?>">
                                <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" id="img_calendar_psip_date" />
                                <script type="text/javascript">
                                    Calendar.setup({
                                        inputField : 'newpayment[psip_date]',
                                        ifFormat : '%Y-%m-%e',
                                        button : 'img_calendar_psip_date',
                                        align : 'Bl',
                                        singleClick : true
                                    });
                                </script>
                            </td>
                            <td align="center">
                                <textarea name="newpayment[psip_notes]" cols="50"></textarea>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
        </center>
    </fieldset>
</div>

<p>&nbsp;</p>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo$this->__('Payments')?></h4>
    </div>
    <fieldset id="my-fieldset">
        <center>
            <div class="grid">
                <table cellspacing="0" class="data">
                    <thead>
                    <tr class="headings">
                        <th class="a-center"><?php echo $this->__('Date'); ?></th>
                        <th class="a-center"><?php echo $this->__('Method'); ?></th>
                        <th class="a-center"><?php echo $this->__('Amount'); ?> (<?php echo $this->getSupplierInvoice()->getCurrency()->getcurrency_code(); ?>)
                        <?php if ($this->getSupplierInvoice()->getCurrency()->getcurrency_code() != Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE)): ?>
                            </th><th class="a-center"><?php echo $this->__('Amount'); ?> (<?php echo Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE); ?>)
                        <?php endif; ?>
                        </th>
                        <th class="a-center"><?php echo $this->__('Notes'); ?></th>
                        <th class="a-center"><?php echo $this->__('Delete'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->getSupplierInvoice()->getPayments()->getSize() > 0): ?>
                            <?php foreach($this->getSupplierInvoice()->getPayments() as $payment): ?>
                                <tr>
                                    <td align="center">
                                        <?php echo $payment->getpsip_date(); ?>
                                    </td>
                                    <td align="center">
                                        <?php echo $payment->getpsip_method(); ?>
                                    </td>
                                    <td align="center">
                                        <?php echo $payment->getpsip_amount(); ?>
                                    </td>
                                    <?php if ($this->getSupplierInvoice()->getCurrency()->getcurrency_code() != Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE)): ?>
                                        <td align="center">
                                            <?php echo $payment->getpsip_amount_base(); ?>
                                        </td>
                                    <?php endif; ?>
                                    <td align="center">
                                        <?php echo $payment->getpsip_notes(); ?>
                                    </td>
                                    <td align="center">
                                        <input type="checkbox" name="deletepayment[]" value="<?php echo $payment->getId(); ?>">
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td align="center" colspan="6">
                                    <?php echo $this->__('No payment'); ?>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </center>
    </fieldset>
</div>