<?php
$switcher = $this->getChild('attribute_store_switch');
$_websiteCollection = $switcher->getWebsiteCollection();
?>
<?php echo $switcher->toHtml(); ?>
<?php echo $this->getFormScopeHtml($this->getForm()); ?>

<?php if (!Mage::app()->isSingleStoreMode()): ?>

    <?php foreach ($_websiteCollection as $_website) : ?>
        <?php echo $this->getFormScopeHtml(null, 'website', $_website->getId()); ?>
        <?php foreach ($switcher->getGroupCollection($_website) as $_group) : ?>
            <?php foreach ($switcher->getStoreCollection($_group) as $_store) : ?>
                <?php echo $this->getFormScopeHtml(null, 'store', $_store->getId()); ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>

<?php endif; ?>