<form id="edit_form" method="POST" name="edit_form" action="<?php echo $this->getUrl('*/*/Save') ?>" enctype="multipart/form-data">

<!-- HEAD CENTER SECTION -->

<?php $this->displaySubTemplate('HeadButtons.phtml'); ?>

<?php $this->displaySubTemplate('MandatoryFormHiddens.phtml'); ?>


<!-- LEFT COLUMN -->
<div class="entry-edit box-left">

    <?php $this->displaySubTemplate('MainInfos.phtml'); ?>

    <?php $this->displaySubTemplate('Object.phtml'); ?>

    <?php $this->displaySubTemplate('PrivateComments.phtml'); ?>

    <?php $this->displaySubTemplate('SecondaryInfos.phtml'); ?>

    <?php $this->displaySubTemplate('CustomerLastOrders.phtml'); ?>

    <?php $this->displaySubTemplate('CustomerLastRmas.phtml'); ?>

    <?php $this->displaySubTemplate('CustomerLastQuotes.phtml'); ?>

    <?php $this->displaySubTemplate('TicketAttachments.phtml'); ?>
  
</div>

<!-- RIGHT COLUMN --> 
<div class="entry-edit box-right">
        
    <?php
    if (Mage::getStoreConfig('crmticket/ticket_data/new_message_field_in_first') == 1) {
        $this->displaySubTemplate('NewMessage.phtml');
        $this->displaySubTemplate('MessagesSection.phtml');
    }else{
        $this->displaySubTemplate('MessagesSection.phtml');
        $this->displaySubTemplate('NewMessage.phtml');
    }
    ?>
        
</div>

<?php Mage::dispatchEvent('crmticket_after_ticket_view', array('ticket' => $this->getTicket())); ?>

</form>

<?php $this->displaySubTemplate('Javascript.phtml'); ?>

<?php
if (Mage::getStoreConfig('cms/wysiwyg/enabled') == 'hidden') {
    $this->displaySubTemplate('Wysiwyg.phtml');
}
?>

<?php $this->displaySubTemplate('AutoSave.phtml'); ?>

