<!DOCTYPE html>
<html>
<head>
    <title>Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/w3.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!--    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">-->
    <!-- Add any other renderers you need; see Use Renderers for more information -->
    <link rel="stylesheet" href="js/lib/player/src/css/mediaelementplayer.css"/>

    <script data-main="js/main" src="js/lib/jquery.js"></script>
    <script data-main="js/main" src="js/lib/vue.js"></script>
    <script data-main="js/main" src="js/lib/player/build/mediaelement-and-player.js"></script>
    <script data-main="js/main" src="js/app/components.js"></script>
</head>

<body>
<div id="app">
    <div class="w3-container w3-amber">
        <h3>{{ch_current.title}}</h3>
    </div>

    <div class="content">
        <?php Vue::app()->getBlockHtml('page/header') ?>
        <?php Vue::app()->getBlockHtml('page/player') ?>

        <div class="w3-bar w3-mobile w3-border w3-round channel_list">
            <?php Vue::app()->getBlockHtml('page/channel') ?>
        </div>

        <?php Vue::app()->getBlockHtml('page/program') ?>

    </div>

</div>

<script>
    <?php $rai = new Video_Rai() ?>
    var data = JSON.parse('<?php echo $rai->getJsonConfig() ?>');

    var vm = new Vue({
        data: data,
    });

    vm.$mount('#app');


    var player = new MediaElementPlayer('videoElement', {
        /**
         * YOU MUST SET THE TYPE WHEN NO SRC IS PROVIDED AT INITIALISATION
         * (This one is not very well documented.. If one leaves the type out, the success event will never fire!!)
         **/
        type: ["video/mp4"],
        features: ['playpause', 'progress', 'current', 'duration', 'tracks', 'volume'],
        mediaElementInitialized: false,
        //more options here..

        success: function (mediaElement, domObject) {
            this.mediaElementInitialized = true;
        },
        error: function (e) {
            alert(e);
        }
    });

</script>


</body>
</html>